# Generated by Django 4.2.1 on 2023-05-26 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_flights_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.CharField(default='ATH', max_length=3),
        ),
        migrations.AddField(
            model_name='flight',
            name='max_seats',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='flight',
            name='number',
            field=models.CharField(default='ION1234', max_length=7, unique=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin',
            field=models.CharField(default='CFU', max_length=3),
        ),
        migrations.AddField(
            model_name='flight',
            name='scheduled',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 12, 0)),
        ),
    ]
