# Generated by Django 4.2.1 on 2023-05-26 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_flight_destination_flight_max_seats_flight_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='current_seats',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Booked Seats'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(default='ATH', max_length=3, verbose_name='Arrival Airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='max_seats',
            field=models.PositiveIntegerField(default=120, verbose_name='Maximum Seat Capacity'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='number',
            field=models.CharField(default='ION1234', max_length=7, unique=True, verbose_name='Flight Code'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.CharField(default='CFU', max_length=3, verbose_name='Departing Airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 12, 0), verbose_name='Departure Time'),
        ),
    ]
