# Generated by Django 4.2.1 on 2023-05-26 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking_passenger_paymentprov_transaction_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentProv',
            new_name='PaymentProvider',
        ),
    ]
