# Generated by Django 4.2.1 on 2023-05-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_paymentprov_paymentprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Transaction ID'),
        ),
    ]
