# Generated by Django 4.2.1 on 2023-05-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Flight ID'),
        ),
    ]
