# Generated by Django 4.2.1 on 2023-05-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_flight_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='transaction_id',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
